// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcAfdMKBGGl1M7oa9B0rkrQEZ8D1khZug',
    appId: '1:886351472574:web:0f9e9206d32fd85d4a7bef',
    messagingSenderId: '886351472574',
    projectId: 'takhotel-b0a4a',
    authDomain: 'takhotel-b0a4a.firebaseapp.com',
    storageBucket: 'takhotel-b0a4a.firebasestorage.app',
    measurementId: 'G-59VRY0Z2Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDprTxRpc81YPKIPwkCcGew9Q6wYrBuLOI',
    appId: '1:886351472574:android:e5e71d0560b6d96f4a7bef',
    messagingSenderId: '886351472574',
    projectId: 'takhotel-b0a4a',
    storageBucket: 'takhotel-b0a4a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcAfdMKBGGl1M7oa9B0rkrQEZ8D1khZug',
    appId: '1:886351472574:web:234076ccd7b4fbeb4a7bef',
    messagingSenderId: '886351472574',
    projectId: 'takhotel-b0a4a',
    authDomain: 'takhotel-b0a4a.firebaseapp.com',
    storageBucket: 'takhotel-b0a4a.firebasestorage.app',
    measurementId: 'G-ZB9CNJE85L',
  );

}